/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Caja;
import clases.MySQL;
import clases.Producto;
import java.util.ArrayList;

/**
 *
 * @author hp desktop
 */
public class NewJFrameVerCaja extends javax.swing.JFrame {
    private NewJFramePrincipal principal;
    private Caja cajaActual;
    private MySQL db;
    /**
     * Creates new form NewJFrameVerCaja
     */
    public NewJFrameVerCaja(NewJFramePrincipal principal, Caja cajaA, MySQL db) {
        this.cajaActual = cajaA;
        this.principal = principal;
        this.db = db;
        initComponents();
        db.mostrarCaja(jTableMov, cajaActual.getIdCaja());
        setLocationRelativeTo(null);
        setResizable(false);
        //setDefaultCloseOperation(0);//anula la CRUZ exit
        setTitle("Colibrí Arte y Cultura - Ver Caja");
        //buscarle lugar! aca no va!
        jTextFieldApertura.setText(this.cajaActual.getMontoApertura().toString());
        jTextFieldApertura.setEditable(false);
        jLabelTotal.setText(jLabelTotal.getText()+this.cajaActual.getMonto().toString());
        
        jButtonPrincipal.setContentAreaFilled(false);
        jButtonPrincipal.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCaja = new javax.swing.JPanel();
        jLabelAperturaCaja = new javax.swing.JLabel();
        jLabelGasto = new javax.swing.JLabel();
        jButtonPrincipal = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jTextFieldApertura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMov = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCaja.setBackground(new java.awt.Color(0, 0, 0));
        jPanelCaja.setForeground(new java.awt.Color(109, 176, 248));
        jPanelCaja.setLayout(null);

        jLabelAperturaCaja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAperturaCaja.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAperturaCaja.setText("Apertura de caja");
        jPanelCaja.add(jLabelAperturaCaja);
        jLabelAperturaCaja.setBounds(10, 20, 140, 15);

        jLabelGasto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelGasto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGasto.setText("Ultimos movimientos");
        jPanelCaja.add(jLabelGasto);
        jLabelGasto.setBounds(150, 90, 130, 15);

        jButtonPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuPrincipal.png"))); // NOI18N
        jButtonPrincipal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPrincipal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrincipalActionPerformed(evt);
            }
        });
        jPanelCaja.add(jButtonPrincipal);
        jButtonPrincipal.setBounds(310, 340, 70, 60);

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotal.setText("Total Parcial: $");
        jPanelCaja.add(jLabelTotal);
        jLabelTotal.setBounds(20, 360, 170, 15);
        jPanelCaja.add(jTextFieldApertura);
        jTextFieldApertura.setBounds(10, 40, 130, 28);

        jTableMov = new javax.swing.JTable() {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        jTableMov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo", "Monto", "Responsable", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(jTableMov);

        jPanelCaja.add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 400, 220);

        jButton1.setText("Ver detalle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelCaja.add(jButton1);
        jButton1.setBounds(200, 340, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja2.png"))); // NOI18N
        jPanelCaja.add(jLabel1);
        jLabel1.setBounds(0, 0, 430, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCaja, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrincipalActionPerformed
       this.principal.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButtonPrincipalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int row = jTableMov.getSelectedRow();        
        String tipo = jTableMov.getModel().getValueAt(row,1).toString();
        if (tipo.equals("Venta")){
            ArrayList<Integer> lista = new ArrayList<Integer>();
            int i = Integer.parseInt(jTableMov.getModel().getValueAt(row,0).toString());
            lista = db.mostrarMovProd(i);
          
            NewJFrameDetalleVenta v = new NewJFrameDetalleVenta(lista, db);
            v.setVisible(true);            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameVerCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameVerCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameVerCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameVerCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameVerCaja(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAperturaCaja;
    private javax.swing.JLabel jLabelGasto;
    private javax.swing.JLabel jLabelTotal;
    public javax.swing.JPanel jPanelCaja;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMov;
    private javax.swing.JTextField jTextFieldApertura;
    // End of variables declaration//GEN-END:variables
}
