/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Caja;
import clases.Movimiento;
import clases.MySQL;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.text.*;
import javax.swing.JOptionPane;

/**
 *
 * @author hp desktop
 */
public class NewJFrameEgreso extends javax.swing.JFrame {
    private NewJFramePrincipal principal;
    private Caja cajaActual;
    private Movimiento m;
    private MySQL db;

    /**
     * Creates new form NewJFrameEgreso
     */
    public NewJFrameEgreso(NewJFramePrincipal principal, Caja cajaA, MySQL db) {
        this.cajaActual = cajaA;
        this.principal = principal;
        this.db = db;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        //setDefaultCloseOperation(0);//anula la CRUZ exit
        setTitle("Colibrí Arte y Cultura - Egreso / Pago");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEgreso = new javax.swing.JPanel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelMonto = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jTextFieldMonto = new javax.swing.JTextField();
        jButtonEgreso = new javax.swing.JButton();
        jButtonMenuPrincipal = new javax.swing.JButton();
        jLabelProveedor = new javax.swing.JLabel();
        jComboBoxProveedor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelEgreso.setBackground(new java.awt.Color(0, 0, 0));
        jPanelEgreso.setForeground(new java.awt.Color(109, 176, 248));
        jPanelEgreso.setLayout(null);

        jLabelDescripcion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescripcion.setText("Descripcion: ");
        jPanelEgreso.add(jLabelDescripcion);
        jLabelDescripcion.setBounds(10, 100, 80, 30);

        jLabelMonto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMonto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMonto.setText("Monto:        $ ");
        jPanelEgreso.add(jLabelMonto);
        jLabelMonto.setBounds(4, 134, 73, 14);

        jTextFieldDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDescripcionKeyTyped(evt);
            }
        });
        jPanelEgreso.add(jTextFieldDescripcion);
        jTextFieldDescripcion.setBounds(81, 105, 193, 20);

        jTextFieldMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMontoActionPerformed(evt);
            }
        });
        jTextFieldMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMontoKeyTyped(evt);
            }
        });
        jPanelEgreso.add(jTextFieldMonto);
        jTextFieldMonto.setBounds(81, 131, 114, 20);

        jButtonEgreso.setText("Cargar Pago");
        jButtonEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEgresoActionPerformed(evt);
            }
        });
        jPanelEgreso.add(jButtonEgreso);
        jButtonEgreso.setBounds(240, 200, 120, 23);

        jButtonMenuPrincipal.setText("Menú Principal");
        jButtonMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuPrincipalActionPerformed(evt);
            }
        });
        jPanelEgreso.add(jButtonMenuPrincipal);
        jButtonMenuPrincipal.setBounds(100, 200, 134, 23);

        jLabelProveedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelProveedor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProveedor.setText("Proveedor: ");
        jPanelEgreso.add(jLabelProveedor);
        jLabelProveedor.setBounds(10, 76, 70, 20);

        jComboBoxProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quimica quillay", "rama", "vasco", "verduleria", "pollos", "mr pan", "huevos", "chino", "helado", "cafe bakan", "dallachiesa", "hielo 42", "la gran miga", "mauca", "mc cain", "nini", "papelera", "purre", "quilmes tolosa", "copete", "otros" }));
        jPanelEgreso.add(jComboBoxProveedor);
        jComboBoxProveedor.setBounds(81, 79, 193, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedores.png"))); // NOI18N
        jPanelEgreso.add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEgreso, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEgreso, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuPrincipalActionPerformed
        this.principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonMenuPrincipalActionPerformed

    private void jButtonEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEgresoActionPerformed

       // generar PAGO!
       try{
            System.out.println(cajaActual.getUser().getUser());

            int eleccion = JOptionPane.showConfirmDialog(null," ¿ DESEA REALIZAR EL PAGO ? ", "Pago / Egreso ", JOptionPane.WARNING_MESSAGE);
            //Date d = new Date();
            //java.sql.Date fecha = new java.sql.Date(d.getTime());
            
            java.util.Date dt = new java.util.Date();
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String fecha = sdf.format(dt);
           
            if (eleccion == JOptionPane.YES_OPTION){
                String pago = jTextFieldMonto.getText();
                Double egreso = Double.parseDouble(pago);
                cajaActual.setMonto(cajaActual.getMonto() - egreso);
                cajaActual.getEgreso().add(jComboBoxProveedor.getSelectedItem()+"#"+jTextFieldDescripcion.getText()+"#"+jTextFieldMonto.getText());                
                m = new Movimiento(egreso, cajaActual.getUser().getUser(), jTextFieldDescripcion.getText(), fecha, jComboBoxProveedor.getSelectedItem().toString(), "Extraccion");
                db.guardarMovimiento(m);
                JOptionPane.showMessageDialog(null, " PAGO REALIZADO ");
                jTextFieldMonto.setText("");
                jTextFieldDescripcion.setText("");

            }else if (eleccion == JOptionPane.CANCEL_OPTION){

            }else if (eleccion == JOptionPane.CLOSED_OPTION){

            }

            //prueba en consola
            for(int x=0;x<cajaActual.getEgreso().size();x++) {
                System.out.println(cajaActual.getEgreso().get(x));
            }
            System.out.println(cajaActual.getMonto());

        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "FORMATO INCORRECTO EN EL INGRESO DE DATOS", "ERROR", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButtonEgresoActionPerformed

    private void jTextFieldMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMontoKeyTyped
        //no deja escribir letras , solamente un solo punto, unicamente deja escribir numeros!
        int k = evt.getKeyChar();
        if ((k >= 46) && (k<= 57) ){
            if (k == 46){
                String dato =  jTextFieldMonto.getText();
                int tam = dato.length();
                for (int i=0; i<=tam; i++){
                    if(dato.contains("."))
                    evt.setKeyChar((char)KeyEvent.VK_CLEAR);

                }
            }if (k == 47){
                evt.setKeyChar((char)KeyEvent.VK_CLEAR);
            }
        }else{
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
            evt.consume();
        }
        if (k == KeyEvent.VK_ENTER){
            jButtonEgreso.doClick();
        }
    }//GEN-LAST:event_jTextFieldMontoKeyTyped

    private void jTextFieldMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMontoActionPerformed

    private void jTextFieldDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionKeyTyped

        presEnterEgreso(evt);
    }//GEN-LAST:event_jTextFieldDescripcionKeyTyped
    public void presEnterEgreso (java.awt.event.KeyEvent evt){
        char teclaPres = evt.getKeyChar();
        if (teclaPres == KeyEvent.VK_ENTER){
           jButtonEgreso.doClick();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameEgreso(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEgreso;
    private javax.swing.JButton jButtonMenuPrincipal;
    private javax.swing.JComboBox<String> jComboBoxProveedor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelMonto;
    private javax.swing.JLabel jLabelProveedor;
    private javax.swing.JPanel jPanelEgreso;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldMonto;
    // End of variables declaration//GEN-END:variables
}
