/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Caja;
import clases.Cuenta;
import clases.MySQL;
import clases.Producto;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author hp desktop
 */

public class NewJFrameMesa extends javax.swing.JFrame {
    private NewJFramePrincipal principal;
    private JButton btn;
    private MySQL db;
    private Caja cajaActual;
    private String ultimoBoton = "prueba";
    private Double total;
    private Cuenta cuenta;
    
    //traje la caja hasta aca solamente. falta sumar precios de productos en la cuenta
    
    public NewJFrameMesa(NewJFramePrincipal principal, MySQL db, JButton btn, Caja cajaA) {
        this.cajaActual= cajaA;
        this.btn = btn;
        this.db = db;
        this.principal = principal;
        
        this.total = 0.0;
        this.cuenta = cuenta;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(0);//anula la CRUZ exit
        setTitle("Colibrí Arte y Cultura - Cuenta");     
        
        //llena lista base datos
        db.llenarJlist(jListPlato);
        
        //jTextFieldTotal.setEditable(false);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMesa = new javax.swing.JPanel();
        jTextFieldPlato = new javax.swing.JTextField();
        jTextFieldIngrediente = new javax.swing.JTextField();
        jScrollPanePlato = new javax.swing.JScrollPane();
        jListPlato = new javax.swing.JList<>();
        jScrollPaneIngrediente = new javax.swing.JScrollPane();
        jListIngrediente = new javax.swing.JList<>();
        jButtonPlato = new javax.swing.JButton();
        jButtonIngrediente = new javax.swing.JButton();
        jLabelPlato = new javax.swing.JLabel();
        jLabelIngrediente = new javax.swing.JLabel();
        jPanelCuenta = new javax.swing.JPanel();
        jButtonBorrar = new javax.swing.JButton();
        jButtonDescuento = new javax.swing.JButton();
        jButtonCerrarCuenta = new javax.swing.JButton();
        jLabelCuenta = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCuenta = new javax.swing.JTable();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabelMesa = new javax.swing.JLabel();
        jTextFieldMesa = new javax.swing.JTextField();
        jCheckBoxMesa = new javax.swing.JCheckBox();
        jButtonMenuPrincipal = new javax.swing.JButton();
        jButtonBorrarCuenta = new javax.swing.JButton();
        jButtonBebidas = new javax.swing.JButton();
        jButtonPostre = new javax.swing.JButton();
        jButtonCafeteria = new javax.swing.JButton();
        jButtonPanqueque = new javax.swing.JButton();
        jButtonTortilla = new javax.swing.JButton();
        jButtonPan1 = new javax.swing.JButton();
        jButtonHamburgesa = new javax.swing.JButton();
        jButtonFritas = new javax.swing.JButton();
        jButtonEnsalada = new javax.swing.JButton();
        jButtonPastas = new javax.swing.JButton();
        jButtonMilanesas = new javax.swing.JButton();
        jButtonPiza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMesa.setBackground(new java.awt.Color(0, 204, 255));

        jTextFieldPlato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPlatoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPlatoKeyReleased(evt);
            }
        });

        jScrollPanePlato.setViewportView(jListPlato);

        jScrollPaneIngrediente.setViewportView(jListIngrediente);

        jButtonPlato.setText("Cargar Plato");
        jButtonPlato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPlatoMouseClicked(evt);
            }
        });
        jButtonPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlatoActionPerformed(evt);
            }
        });

        jButtonIngrediente.setText("Cargar Ingrediente");

        jLabelPlato.setText("Buscar");

        jLabelIngrediente.setText("Buscar Ingrediente");

        jPanelCuenta.setBackground(new java.awt.Color(51, 153, 255));

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBorrarMouseClicked(evt);
            }
        });

        jButtonDescuento.setText("Aplicar Descuento");

        jButtonCerrarCuenta.setText("Cerrar Cuenta");
        jButtonCerrarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCerrarCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCerrarCuentaMouseEntered(evt);
            }
        });

        jLabelCuenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCuenta.setText("CUENTA");

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTotal.setText("TOTAL: $ ");

        jTableCuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTableCuenta);

        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCuentaLayout = new javax.swing.GroupLayout(jPanelCuenta);
        jPanelCuenta.setLayout(jPanelCuentaLayout);
        jPanelCuentaLayout.setHorizontalGroup(
            jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCuentaLayout.createSequentialGroup()
                        .addGroup(jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCuentaLayout.createSequentialGroup()
                                .addComponent(jLabelTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCerrarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCuentaLayout.createSequentialGroup()
                        .addComponent(jLabelCuenta)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCuentaLayout.setVerticalGroup(
            jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCuentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCuentaLayout.createSequentialGroup()
                        .addComponent(jButtonBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDescuento))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal)
                    .addComponent(jButtonCerrarCuenta)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        jLabelMesa.setText("COMENTARIO: ");

        jTextFieldMesa.setText(this.btn.getText());
        jTextFieldMesa.setEditable(false);

        jCheckBoxMesa.setSelected(true);
        jCheckBoxMesa.setBackground(new java.awt.Color(0, 204, 255));
        jCheckBoxMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxMesaMouseClicked(evt);
            }
        });

        jButtonMenuPrincipal.setText("MENU PRINCIPAL");
        jButtonMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuPrincipalActionPerformed(evt);
            }
        });

        jButtonBorrarCuenta.setText("BORRAR CUENTA");
        jButtonBorrarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBorrarCuentaMouseClicked(evt);
            }
        });

        jButtonPiza.setIcon(new ImageIcon("../imagenes/iconoPiza.jpg"));
        jButtonBebidas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoBebidas.jpg"))); // NOI18N
        jButtonBebidas.setText("Bebidas");
        jButtonBebidas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBebidas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBebidasActionPerformed(evt);
            }
        });

        jButtonPiza.setIcon(new ImageIcon("../imagenes/iconoPiza.jpg"));
        jButtonPostre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPostre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flan.jpg"))); // NOI18N
        jButtonPostre.setText("Postres");
        jButtonPostre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPostre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPostre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPostreActionPerformed(evt);
            }
        });

        jButtonPiza.setIcon(new ImageIcon("../imagenes/iconoPiza.jpg"));
        jButtonCafeteria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCafeteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoCafe.jpg"))); // NOI18N
        jButtonCafeteria.setText("Cafeteria");
        jButtonCafeteria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCafeteria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCafeteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCafeteriaActionPerformed(evt);
            }
        });

        jButtonPiza.setIcon(new ImageIcon("../imagenes/iconoPiza.jpg"));
        jButtonPanqueque.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPanqueque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconPancakes.jpg"))); // NOI18N
        jButtonPanqueque.setText("Panqueques");
        jButtonPanqueque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPanqueque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPanqueque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPanquequeActionPerformed(evt);
            }
        });

        jButtonTortilla.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonTortilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tortilla.jpg"))); // NOI18N
        jButtonTortilla.setText("Tortillas");
        jButtonTortilla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTortilla.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonTortilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTortillaActionPerformed(evt);
            }
        });

        jButtonPan1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pan.jpg"))); // NOI18N
        jButtonPan1.setText("Pan de 10");
        jButtonPan1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPan1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPan1ActionPerformed(evt);
            }
        });
        jButtonPan1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonPan1KeyReleased(evt);
            }
        });

        jButtonHamburgesa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonHamburgesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hamburgesa.jpg"))); // NOI18N
        jButtonHamburgesa.setText("Hamburgesa");
        jButtonHamburgesa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonHamburgesa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonFritas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonFritas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fritas.jpg"))); // NOI18N
        jButtonFritas.setText("Papas fritas");
        jButtonFritas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFritas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFritas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFritasActionPerformed(evt);
            }
        });

        jButtonEnsalada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEnsalada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ensalada.png"))); // NOI18N
        jButtonEnsalada.setText("Ensaladas");
        jButtonEnsalada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEnsalada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEnsalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnsaladaActionPerformed(evt);
            }
        });

        jButtonPastas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPastas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tallarines.jpg"))); // NOI18N
        jButtonPastas.setText("Pastas");
        jButtonPastas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPastas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPastas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPastasActionPerformed(evt);
            }
        });

        jButtonPiza.setIcon(new ImageIcon("../imagenes/iconoPiza.jpg"));
        jButtonMilanesas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonMilanesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/milanesa.jpg"))); // NOI18N
        jButtonMilanesas.setText("Milanesas");
        jButtonMilanesas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMilanesas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonPiza.setIcon(new ImageIcon("../imagenes/iconoPiza.jpg"));
        jButtonPiza.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piza.jpg"))); // NOI18N
        jButtonPiza.setText("Pizza");
        jButtonPiza.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPiza.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMesaLayout = new javax.swing.GroupLayout(jPanelMesa);
        jPanelMesa.setLayout(jPanelMesaLayout);
        jPanelMesaLayout.setHorizontalGroup(
            jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelMesaLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jButtonPan1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonPanqueque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelMesaLayout.createSequentialGroup()
                            .addComponent(jButtonMilanesas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(jButtonEnsalada, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelMesaLayout.createSequentialGroup()
                            .addComponent(jButtonTortilla, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonPiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelMesaLayout.createSequentialGroup()
                        .addComponent(jButtonPastas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHamburgesa, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMesaLayout.createSequentialGroup()
                        .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFritas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCafeteria, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPostre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelMesaLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabelMesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxMesa)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMesaLayout.createSequentialGroup()
                        .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonPlato, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelMesaLayout.createSequentialGroup()
                                .addComponent(jLabelPlato)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldPlato, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPanePlato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMesaLayout.createSequentialGroup()
                                .addComponent(jButtonBorrarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelMesaLayout.createSequentialGroup()
                                .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelIngrediente)
                                    .addComponent(jTextFieldIngrediente)
                                    .addComponent(jButtonIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPaneIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanelCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))))
        );
        jPanelMesaLayout.setVerticalGroup(
            jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMesaLayout.createSequentialGroup()
                        .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxMesa)
                            .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelMesa)
                                .addComponent(jTextFieldMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelMesaLayout.createSequentialGroup()
                                .addComponent(jLabelPlato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPanePlato, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPlato))
                            .addGroup(jPanelMesaLayout.createSequentialGroup()
                                .addComponent(jLabelIngrediente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPaneIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonIngrediente)))
                        .addGap(55, 55, 55)
                        .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBorrarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMesaLayout.createSequentialGroup()
                        .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelMesaLayout.createSequentialGroup()
                                .addComponent(jButtonPanqueque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPiza))
                            .addGroup(jPanelMesaLayout.createSequentialGroup()
                                .addComponent(jButtonPan1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonTortilla)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPastas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHamburgesa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonMilanesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEnsalada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBebidas)
                            .addComponent(jButtonFritas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCafeteria)
                            .addComponent(jButtonPostre))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuPrincipalActionPerformed
       this.principal.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButtonMenuPrincipalActionPerformed

    private void jButtonCerrarCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarCuentaMouseEntered
        // TODO add your handling code here:
        
        //lo hice al pedo!
    }//GEN-LAST:event_jButtonCerrarCuentaMouseEntered

    private void jButtonCerrarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarCuentaMouseClicked
       int eleccion = JOptionPane.showConfirmDialog(null,jLabelTotal.getText()+jTextFieldTotal.getText(), " CERRAR CUENTA ", JOptionPane.WARNING_MESSAGE);
       if (eleccion == JOptionPane.YES_OPTION){
           Date fecha = new Date();
           java.sql.Date fechasql = new java.sql.Date(fecha.getTime());
           Cuenta c = new Cuenta(total, fechasql,"");
           db.guardarCuenta(c);
           this.btn.setBackground(Color.green);
           this.principal.setVisible(true);
           this.principal.getMesas().remove(btn);
           this.dispose();      
       }else if (eleccion == JOptionPane.CANCEL_OPTION){
           
       }else if (eleccion == JOptionPane.CLOSED_OPTION){
           
       } 
    }//GEN-LAST:event_jButtonCerrarCuentaMouseClicked

    private void jCheckBoxMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxMesaMouseClicked
        if (jCheckBoxMesa.isSelected()){
            jTextFieldMesa.setEditable(false);
        }else{
            jTextFieldMesa.setEditable(true);
        }
    }//GEN-LAST:event_jCheckBoxMesaMouseClicked

    private void jButtonPlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlatoMouseClicked
        String opcion = jListPlato.getSelectedValue();
        //System.out.println(opcion);
        Producto p = db.getProducto(opcion);
        total = total + p.getPrecio();
        jTextFieldTotal.setText(total.toString() );
        //System.out.println(p.toString());
        
        DefaultTableModel model = (DefaultTableModel) jTableCuenta.getModel();
        Object[] row = new Object[3];
        row[0] = p.getNombre();
        row[1] =  1;
        row[2] =  p.getPrecio();
        model.addRow(row);
        jTableCuenta.setModel(model);
        //float precio = db.getPrecioProd(opcion);
        //DefaultListModel  modelo = (DefaultListModel) jListCuenta.getModel();
        //modelo.addElement(precio);
        //jListCuenta.setModel(modelo);  
    }//GEN-LAST:event_jButtonPlatoMouseClicked
    public JButton getButton(){
        return this.btn;
    }
    private void jButtonBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBorrarMouseClicked
        
        int i = jTableCuenta.getSelectedRow();
        
        DefaultTableModel model = (DefaultTableModel) jTableCuenta.getModel();
        total = total - (float) jTableCuenta.getValueAt(i, 2);
        jTextFieldTotal.setText(total.toString());
        model.removeRow(i);
        
        
        /*String opcion = jListCuenta.getSelectedValue();
        System.out.println(opcion);
        DefaultListModel  modelo = (DefaultListModel) jListCuenta.getModel();
        modelo.removeElement(opcion);
        jListCuenta.setModel(modelo);  */
    }//GEN-LAST:event_jButtonBorrarMouseClicked

    private void jButtonBorrarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBorrarCuentaMouseClicked
       int eleccion = JOptionPane.showConfirmDialog(null,"¿ DESEA ELIMINAR LA CUENTA ? ", " BORRAR CUENTA ", JOptionPane.WARNING_MESSAGE);
       if (eleccion == JOptionPane.YES_OPTION){
          
           this.btn.setBackground(Color.green);
           this.principal.setVisible(true);
           this.principal.getMesas().remove(btn);
           this.dispose();
       }else if (eleccion == JOptionPane.CANCEL_OPTION){
           
       }else if (eleccion == JOptionPane.CLOSED_OPTION){
           
       }
    }//GEN-LAST:event_jButtonBorrarCuentaMouseClicked

    private void jTextFieldPlatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPlatoKeyPressed
       
    }//GEN-LAST:event_jTextFieldPlatoKeyPressed

    private void jButtonTortillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTortillaActionPerformed
         db.buscarPorCategoria(jListPlato, jButtonTortilla.getText());
         ultimoBoton = jButtonTortilla.getText();
    }//GEN-LAST:event_jButtonTortillaActionPerformed

    private void jButtonPan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPan1ActionPerformed
         db.buscarPorCategoria(jListPlato, jButtonPan1.getText());
         ultimoBoton = jButtonPan1.getText();
    }//GEN-LAST:event_jButtonPan1ActionPerformed

    private void jButtonPanquequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPanquequeActionPerformed
        db.buscarPorCategoria(jListPlato, jButtonPanqueque.getText()); 
        ultimoBoton = jButtonPanqueque.getText();
    }//GEN-LAST:event_jButtonPanquequeActionPerformed

    private void jButtonCafeteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCafeteriaActionPerformed
         db.buscarPorCategoria(jListPlato, jButtonCafeteria.getText());
         ultimoBoton = jButtonCafeteria.getText();
    }//GEN-LAST:event_jButtonCafeteriaActionPerformed

    private void jButtonPizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPizaActionPerformed
         db.buscarPorCategoria(jListPlato, jButtonPiza.getText());
         ultimoBoton = jButtonPiza.getText();
    }//GEN-LAST:event_jButtonPizaActionPerformed

    private void jButtonPan1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonPan1KeyReleased
               // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPan1KeyReleased

    private void jButtonPastasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPastasActionPerformed
         db.buscarPorCategoria(jListPlato, jButtonPastas.getText());
         ultimoBoton = jButtonPastas.getText();
    }//GEN-LAST:event_jButtonPastasActionPerformed

    private void jButtonEnsaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnsaladaActionPerformed
         db.buscarPorCategoria(jListPlato, jButtonEnsalada.getText());
         ultimoBoton = jButtonEnsalada.getText();
    }//GEN-LAST:event_jButtonEnsaladaActionPerformed

    private void jButtonFritasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFritasActionPerformed
        db.buscarPorCategoria(jListPlato, jButtonFritas.getText());
        ultimoBoton = jButtonFritas.getText();
    }//GEN-LAST:event_jButtonFritasActionPerformed

    private void jButtonBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBebidasActionPerformed
        db.buscarPorCategoria(jListPlato, jButtonBebidas.getText());
        ultimoBoton = jButtonBebidas.getText();
    }//GEN-LAST:event_jButtonBebidasActionPerformed

    private void jButtonPostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPostreActionPerformed
        db.buscarPorCategoria(jListPlato, jButtonPostre.getText());
        ultimoBoton = jButtonPostre.getText();
    }//GEN-LAST:event_jButtonPostreActionPerformed

    private void jTextFieldPlatoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPlatoKeyReleased
       db.buscarPlatos(jListPlato, jTextFieldPlato.getText(), ultimoBoton);       
    }//GEN-LAST:event_jTextFieldPlatoKeyReleased

    private void jButtonPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlatoActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameMesa(null,null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBebidas;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBorrarCuenta;
    private javax.swing.JButton jButtonCafeteria;
    private javax.swing.JButton jButtonCerrarCuenta;
    private javax.swing.JButton jButtonDescuento;
    private javax.swing.JButton jButtonEnsalada;
    private javax.swing.JButton jButtonFritas;
    private javax.swing.JButton jButtonHamburgesa;
    private javax.swing.JButton jButtonIngrediente;
    private javax.swing.JButton jButtonMenuPrincipal;
    private javax.swing.JButton jButtonMilanesas;
    private javax.swing.JButton jButtonPan1;
    private javax.swing.JButton jButtonPanqueque;
    private javax.swing.JButton jButtonPastas;
    private javax.swing.JButton jButtonPiza;
    private javax.swing.JButton jButtonPlato;
    private javax.swing.JButton jButtonPostre;
    private javax.swing.JButton jButtonTortilla;
    private javax.swing.JCheckBox jCheckBoxMesa;
    private javax.swing.JLabel jLabelCuenta;
    private javax.swing.JLabel jLabelIngrediente;
    private javax.swing.JLabel jLabelMesa;
    private javax.swing.JLabel jLabelPlato;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JList<String> jListIngrediente;
    private javax.swing.JList<String> jListPlato;
    private javax.swing.JPanel jPanelCuenta;
    private javax.swing.JPanel jPanelMesa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneIngrediente;
    private javax.swing.JScrollPane jScrollPanePlato;
    private javax.swing.JTable jTableCuenta;
    private javax.swing.JTextField jTextFieldIngrediente;
    private javax.swing.JTextField jTextFieldMesa;
    private javax.swing.JTextField jTextFieldPlato;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
