/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Caja;
import clases.Movimiento;
import clases.MySQL;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.Iterator;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author hp desktop
 */
public class NewJFrameMovimientoCaja extends javax.swing.JFrame {
    private MySQL db;
    private NewJFramePrincipal principal;
    private Caja cajaActual;
    private Movimiento m;
    /**
     * Creates new form NewJFrameMovimientoCaja
     */
    public NewJFrameMovimientoCaja(NewJFramePrincipal principal, Caja cajaA, MySQL bd) {
        this.db= bd;
        this.cajaActual = cajaA;
        this.principal = principal;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        //setDefaultCloseOperation(0);//anula la CRUZ exit
        setTitle("Colibrí Arte y Cultura - Movimiento de Caja");
        
        jButtonMenuPrincipal.setContentAreaFilled(false);
        jButtonMenuPrincipal.setBorderPainted(false);
        
        jButtonMovimiento.setContentAreaFilled(false);
        jButtonMovimiento.setBorderPainted(false);        
                    

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMovimiento = new javax.swing.ButtonGroup();
        jPanelMovCaja = new javax.swing.JPanel();
        jLabelDescripcion = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jLabelMonto = new javax.swing.JLabel();
        jTextFieldMonto = new javax.swing.JTextField();
        jButtonMovimiento = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonMenuPrincipal = new javax.swing.JButton();
        jRadioButtonDeposito = new javax.swing.JRadioButton();
        jRadioButtonExtraccion = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMovCaja.setBackground(new java.awt.Color(0, 0, 0));
        jPanelMovCaja.setForeground(new java.awt.Color(109, 176, 248));
        jPanelMovCaja.setLayout(null);

        jLabelDescripcion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescripcion.setText("Descripcion del movimiento");
        jPanelMovCaja.add(jLabelDescripcion);
        jLabelDescripcion.setBounds(10, 75, 156, 14);

        jTextFieldDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescripcionActionPerformed(evt);
            }
        });
        jTextFieldDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDescripcionKeyTyped(evt);
            }
        });
        jPanelMovCaja.add(jTextFieldDescripcion);
        jTextFieldDescripcion.setBounds(181, 72, 220, 20);

        jLabelMonto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMonto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMonto.setText("Monto        $");
        jPanelMovCaja.add(jLabelMonto);
        jLabelMonto.setBounds(16, 132, 67, 14);

        jTextFieldMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMontoKeyTyped(evt);
            }
        });
        jPanelMovCaja.add(jTextFieldMonto);
        jTextFieldMonto.setBounds(91, 129, 160, 20);

        jButtonMovimiento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonMovimiento.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/realizarpago32x32.png"))); // NOI18N
        jButtonMovimiento.setText("Realizar Movimiento");
        jButtonMovimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMovimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMovimientoActionPerformed(evt);
            }
        });
        jPanelMovCaja.add(jButtonMovimiento);
        jButtonMovimiento.setBounds(259, 231, 160, 59);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario");
        jPanelMovCaja.add(jLabelUsuario);
        jLabelUsuario.setBounds(16, 163, 70, 14);

        jTextFieldUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldUsuarioKeyTyped(evt);
            }
        });
        jPanelMovCaja.add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(93, 160, 160, 20);

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Contraseña");
        jPanelMovCaja.add(jLabelPassword);
        jLabelPassword.setBounds(16, 194, 80, 14);

        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyTyped(evt);
            }
        });
        jPanelMovCaja.add(jPasswordField);
        jPasswordField.setBounds(93, 191, 160, 20);

        jButtonMenuPrincipal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuPrincipal32x32(3).png"))); // NOI18N
        jButtonMenuPrincipal.setText("Menu Principal");
        jButtonMenuPrincipal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMenuPrincipal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuPrincipalActionPerformed(evt);
            }
        });
        jPanelMovCaja.add(jButtonMenuPrincipal);
        jButtonMenuPrincipal.setBounds(140, 230, 120, 60);

        jRadioButtonDeposito.setBackground(new java.awt.Color(106, 79, 72));
        buttonGroupMovimiento.add(jRadioButtonDeposito);
        jRadioButtonDeposito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonDeposito.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDeposito.setText("Depósito");
        jPanelMovCaja.add(jRadioButtonDeposito);
        jRadioButtonDeposito.setBounds(16, 99, 100, 23);

        jRadioButtonExtraccion.setBackground(new java.awt.Color(106, 79, 72));
        buttonGroupMovimiento.add(jRadioButtonExtraccion);
        jRadioButtonExtraccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonExtraccion.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonExtraccion.setText("Extracción");
        jPanelMovCaja.add(jRadioButtonExtraccion);
        jRadioButtonExtraccion.setBounds(150, 100, 110, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        jButton1.setText("Generar Reporte");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelMovCaja.add(jButton1);
        jButton1.setBounds(0, 230, 140, 60);

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/movimientodecaja3.png"))); // NOI18N
        jPanelMovCaja.add(jLabelFondo);
        jLabelFondo.setBounds(0, 0, 420, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMovCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMovCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescripcionActionPerformed

    private void jButtonMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMovimientoActionPerformed
         try{ 
            // falta la parte de la validacion de usuario
                int eleccion = JOptionPane.showConfirmDialog(null," ¿ DESEA REALIZAR EL MOVIMIENTO ? ", "CERRAR CUENTA ", JOptionPane.WARNING_MESSAGE);
                if (eleccion == JOptionPane.YES_OPTION){
                    boolean actual = this.db.validarLogin(jPasswordField, jTextFieldUsuario);
                    if (actual){  
                         String movStr = jTextFieldMonto.getText();
                         Double mov = Double.parseDouble(movStr);
                         java.util.Date dt = new java.util.Date();
                         java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm");
                         String fecha = sdf.format(dt);
                         System.out.println(fecha);
                         if (jRadioButtonDeposito.isSelected()){
                            cajaActual.setMonto(cajaActual.getMonto() + mov);
                            cajaActual.getMovimiento().add("+"+jTextFieldDescripcion.getText()+"#"+jTextFieldUsuario.getText());
                            JOptionPane.showMessageDialog(null, " MOVIMIENTO REALIZADO ");
                            String responsable = jTextFieldUsuario.getText();
                             m = new Movimiento (mov, responsable, jTextFieldDescripcion.getText(), fecha, "", "Deposito", cajaActual.getIdCaja());
                             System.out.println(responsable);
                             db.guardarMovimiento(m); 
                            jTextFieldMonto.setText("");
                             jTextFieldDescripcion.setText("");
                             jTextFieldUsuario.setText("");
                             jPasswordField.setText(""); 
                             
                             
                        }   else if (jRadioButtonExtraccion.isSelected()){
                            cajaActual.setMonto(cajaActual.getMonto() - mov);
                            cajaActual.getMovimiento().add("-"+jTextFieldDescripcion.getText()+""
                                    + "#"+jTextFieldUsuario.getText());
                            JOptionPane.showMessageDialog(null, " MOVIMIENTO REALIZADO ");
                             m = new Movimiento (mov, jTextFieldUsuario.getText(), jTextFieldDescripcion.getText(), fecha, "", "Extraccion", cajaActual.getIdCaja());
                             db.guardarMovimiento(m);
                             jTextFieldMonto.setText("");
                             jTextFieldDescripcion.setText("");
                             jTextFieldUsuario.setText("");
                             jPasswordField.setText("");
                            
                        } else {
                             JOptionPane.showMessageDialog(null, " Debes seleccionar entre Extraccion o Deposito antes de realizar el movimiento ");
                        }
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "Error en el ingreso de datos del usuario");
                    }
                }else if (eleccion == JOptionPane.CANCEL_OPTION){
                
                }else if (eleccion == JOptionPane.CLOSED_OPTION){
           
                } 
            
            //prueba en consola
            Iterator<String> itr = this.cajaActual.getMovimiento().iterator();
            while (itr.hasNext()) {
               String element = itr.next();
               System.out.println(element);
            }
            System.out.println(cajaActual.getMonto());
            
            //mensaje operacion exitosa
                     
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "FORMATO INCORRECTO EN EL INGRESO DE DATOS", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
       
       
    }//GEN-LAST:event_jButtonMovimientoActionPerformed

    private void jButtonMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuPrincipalActionPerformed
       this.principal.setVisible(true);
       dispose();
       
    }//GEN-LAST:event_jButtonMenuPrincipalActionPerformed

    private void jTextFieldMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMontoKeyTyped
       //no deja escribir letras , solamente un solo punto, unicamente deja escribir numeros!
       int k = evt.getKeyChar();
       if ((k >= 46) && (k<= 57) ){
          if (k == 46){
             String dato =  jTextFieldMonto.getText();
             int tam = dato.length();
             for (int i=0; i<=tam; i++){
                 if(dato.contains("."))
                     evt.setKeyChar((char)KeyEvent.VK_CLEAR);
                 
                 
             }
          }if (k == 47){
              evt.setKeyChar((char)KeyEvent.VK_CLEAR);
          } 
       }else{
           evt.setKeyChar((char)KeyEvent.VK_CLEAR);
           evt.consume();
       }if (k == KeyEvent.VK_ENTER){
           jButtonMovimiento.doClick();
       }
    }//GEN-LAST:event_jTextFieldMontoKeyTyped

    private void jTextFieldDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionKeyTyped
       presEnterMovimientoCaja(evt);
    }//GEN-LAST:event_jTextFieldDescripcionKeyTyped

    private void jTextFieldUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioKeyTyped
        presEnterMovimientoCaja(evt);
    }//GEN-LAST:event_jTextFieldUsuarioKeyTyped

    private void jPasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyTyped
        presEnterMovimientoCaja(evt);
    }//GEN-LAST:event_jPasswordFieldKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public void presEnterMovimientoCaja (java.awt.event.KeyEvent evt){
        char teclaPres = evt.getKeyChar();
        if (teclaPres == KeyEvent.VK_ENTER){
           jButtonMovimiento.doClick();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameMovimientoCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameMovimientoCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameMovimientoCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameMovimientoCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameMovimientoCaja(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupMovimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonMenuPrincipal;
    private javax.swing.JButton jButtonMovimiento;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelMonto;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelMovCaja;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JRadioButton jRadioButtonDeposito;
    private javax.swing.JRadioButton jRadioButtonExtraccion;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldMonto;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
